"""add_sequence_number_to_issues

Revision ID: 5021f9f71246
Revises: 5653e1b296d1
Create Date: 2026-04-27 00:08:33.794914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5021f9f71246'
down_revision: Union[str, Sequence[str], None] = '5653e1b296d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add as nullable first so existing rows don't violate NOT NULL
    op.add_column('issues', sa.Column('sequence_number', sa.Integer(), nullable=True))

    # Backfill: assign sequential numbers per project ordered by creation time
    op.execute("""
        UPDATE issues i
        SET sequence_number = sub.rn
        FROM (
            SELECT id, ROW_NUMBER() OVER (
                PARTITION BY project_id ORDER BY created_at ASC
            ) AS rn
            FROM issues
        ) sub
        WHERE i.id = sub.id
    """)

    # Now enforce NOT NULL and add unique constraint
    op.alter_column('issues', 'sequence_number', nullable=False)
    op.create_unique_constraint('uq_issue_project_sequence', 'issues', ['project_id', 'sequence_number'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_issue_project_sequence', 'issues', type_='unique')
    op.drop_column('issues', 'sequence_number')
    # ### end Alembic commands ###
