"""add_git_pull_requests_and_commits

Revision ID: b70ec5e04096
Revises: 5021f9f71246
Create Date: 2026-04-27 00:39:03.845225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70ec5e04096'
down_revision: Union[str, Sequence[str], None] = '5021f9f71246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_commits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('sha', sa.String(length=64), nullable=False),
    sa.Column('short_sha', sa.String(length=8), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_email', sa.String(length=255), nullable=True),
    sa.Column('author_avatar', sa.String(length=1000), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'sha', name='uq_git_commit_provider_sha')
    )
    op.create_index(op.f('ix_git_commits_issue_id'), 'git_commits', ['issue_id'], unique=False)
    op.create_table('git_pull_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('author_login', sa.String(length=255), nullable=True),
    sa.Column('author_avatar', sa.String(length=1000), nullable=True),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'pr_id', name='uq_git_pr_provider_id')
    )
    op.create_index(op.f('ix_git_pull_requests_issue_id'), 'git_pull_requests', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_git_pull_requests_issue_id'), table_name='git_pull_requests')
    op.drop_table('git_pull_requests')
    op.drop_index(op.f('ix_git_commits_issue_id'), table_name='git_commits')
    op.drop_table('git_commits')
    # ### end Alembic commands ###
